"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class LineInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    OLD_LINE_NUMBER_FIELD_NUMBER: builtins.int
    NEW_LINE_NUMBER_FIELD_NUMBER: builtins.int
    LINE_TYPE_FIELD_NUMBER: builtins.int
    LINE_FIELD_NUMBER: builtins.int
    old_line_number: builtins.int
    new_line_number: builtins.int
    line_type: typing.Text
    line: typing.Text
    def __init__(self,
        *,
        old_line_number: builtins.int = ...,
        new_line_number: builtins.int = ...,
        line_type: typing.Text = ...,
        line: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["line",b"line","line_type",b"line_type","new_line_number",b"new_line_number","old_line_number",b"old_line_number"]) -> None: ...
global___LineInfo = LineInfo

class HunkBoundary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    OPERATION_TYPE_FIELD_NUMBER: builtins.int
    start: builtins.int
    end: builtins.int
    operation_type: typing.Text
    def __init__(self,
        *,
        start: builtins.int = ...,
        end: builtins.int = ...,
        operation_type: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["end",b"end","operation_type",b"operation_type","start",b"start"]) -> None: ...
global___HunkBoundary = HunkBoundary

class HunkInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HEADER_FIELD_NUMBER: builtins.int
    LINES_FIELD_NUMBER: builtins.int
    TOTAL_BOUNDARY_FIELD_NUMBER: builtins.int
    INSERTIONS_BOUNDARY_FIELD_NUMBER: builtins.int
    DELETIONS_BOUNDARY_FIELD_NUMBER: builtins.int
    header: typing.Text
    @property
    def lines(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LineInfo]: ...
    @property
    def total_boundary(self) -> global___HunkBoundary: ...
    @property
    def insertions_boundary(self) -> global___HunkBoundary: ...
    @property
    def deletions_boundary(self) -> global___HunkBoundary: ...
    def __init__(self,
        *,
        header: typing.Text = ...,
        lines: typing.Optional[typing.Iterable[global___LineInfo]] = ...,
        total_boundary: typing.Optional[global___HunkBoundary] = ...,
        insertions_boundary: typing.Optional[global___HunkBoundary] = ...,
        deletions_boundary: typing.Optional[global___HunkBoundary] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["deletions_boundary",b"deletions_boundary","insertions_boundary",b"insertions_boundary","total_boundary",b"total_boundary"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["deletions_boundary",b"deletions_boundary","header",b"header","insertions_boundary",b"insertions_boundary","lines",b"lines","total_boundary",b"total_boundary"]) -> None: ...
global___HunkInfo = HunkInfo

class PatchInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    OLD_FILE_FIELD_NUMBER: builtins.int
    NEW_FILE_FIELD_NUMBER: builtins.int
    OLD_SOURCE_FIELD_NUMBER: builtins.int
    NEW_SOURCE_FIELD_NUMBER: builtins.int
    HUNKS_FIELD_NUMBER: builtins.int
    old_file: typing.Text
    new_file: typing.Text
    old_source: typing.Text
    new_source: typing.Text
    @property
    def hunks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HunkInfo]: ...
    def __init__(self,
        *,
        old_file: typing.Text = ...,
        new_file: typing.Text = ...,
        old_source: typing.Text = ...,
        new_source: typing.Text = ...,
        hunks: typing.Optional[typing.Iterable[global___HunkInfo]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["hunks",b"hunks","new_file",b"new_file","new_source",b"new_source","old_file",b"old_file","old_source",b"old_source"]) -> None: ...
global___PatchInfo = PatchInfo

class GitResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    REPO_FIELD_NUMBER: builtins.int
    INITIAL_REF_FIELD_NUMBER: builtins.int
    TERMINAL_REF_FIELD_NUMBER: builtins.int
    PATCHES_FIELD_NUMBER: builtins.int
    repo: typing.Text
    initial_ref: typing.Text
    terminal_ref: typing.Text
    @property
    def patches(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PatchInfo]: ...
    def __init__(self,
        *,
        repo: typing.Text = ...,
        initial_ref: typing.Text = ...,
        terminal_ref: typing.Text = ...,
        patches: typing.Optional[typing.Iterable[global___PatchInfo]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["initial_ref",b"initial_ref","patches",b"patches","repo",b"repo","terminal_ref",b"terminal_ref"]) -> None: ...
global___GitResult = GitResult
