"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import git_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class DefinitionParent(google.protobuf.message.Message):
    """DefinitionParent represents a parent scope for a piece of Locust metadata."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    LINE_FIELD_NUMBER: builtins.int
    name: typing.Text
    line: builtins.int
    def __init__(self,
        *,
        name: typing.Text = ...,
        line: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["line",b"line","name",b"name"]) -> None: ...
global___DefinitionParent = DefinitionParent

class RawDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    CHANGE_TYPE_FIELD_NUMBER: builtins.int
    LINE_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    END_LINE_FIELD_NUMBER: builtins.int
    END_OFFSET_FIELD_NUMBER: builtins.int
    PARENT_FIELD_NUMBER: builtins.int
    name: typing.Text
    change_type: typing.Text
    line: builtins.int
    offset: builtins.int
    end_line: builtins.int
    end_offset: builtins.int
    @property
    def parent(self) -> global___DefinitionParent: ...
    def __init__(self,
        *,
        name: typing.Text = ...,
        change_type: typing.Text = ...,
        line: builtins.int = ...,
        offset: builtins.int = ...,
        end_line: builtins.int = ...,
        end_offset: builtins.int = ...,
        parent: typing.Optional[global___DefinitionParent] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["parent",b"parent"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["change_type",b"change_type","end_line",b"end_line","end_offset",b"end_offset","line",b"line","name",b"name","offset",b"offset","parent",b"parent"]) -> None: ...
global___RawDefinition = RawDefinition

class LocustChange(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    CHANGE_TYPE_FIELD_NUMBER: builtins.int
    FILEPATH_FIELD_NUMBER: builtins.int
    REVISION_FIELD_NUMBER: builtins.int
    LINE_FIELD_NUMBER: builtins.int
    CHANGED_LINES_FIELD_NUMBER: builtins.int
    TOTAL_LINES_FIELD_NUMBER: builtins.int
    PARENT_FIELD_NUMBER: builtins.int
    name: typing.Text
    change_type: typing.Text
    filepath: typing.Text
    revision: typing.Text
    line: builtins.int
    changed_lines: builtins.int
    total_lines: builtins.int
    @property
    def parent(self) -> global___DefinitionParent: ...
    def __init__(self,
        *,
        name: typing.Text = ...,
        change_type: typing.Text = ...,
        filepath: typing.Text = ...,
        revision: typing.Text = ...,
        line: builtins.int = ...,
        changed_lines: builtins.int = ...,
        total_lines: builtins.int = ...,
        parent: typing.Optional[global___DefinitionParent] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["parent",b"parent"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["change_type",b"change_type","changed_lines",b"changed_lines","filepath",b"filepath","line",b"line","name",b"name","parent",b"parent","revision",b"revision","total_lines",b"total_lines"]) -> None: ...
global___LocustChange = LocustChange

class ParseResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    REPO_FIELD_NUMBER: builtins.int
    INITIAL_REF_FIELD_NUMBER: builtins.int
    TERMINAL_REF_FIELD_NUMBER: builtins.int
    PATCHES_FIELD_NUMBER: builtins.int
    CHANGES_FIELD_NUMBER: builtins.int
    repo: typing.Text
    initial_ref: typing.Text
    terminal_ref: typing.Text
    @property
    def patches(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[git_pb2.PatchInfo]: ...
    @property
    def changes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LocustChange]: ...
    def __init__(self,
        *,
        repo: typing.Text = ...,
        initial_ref: typing.Text = ...,
        terminal_ref: typing.Text = ...,
        patches: typing.Optional[typing.Iterable[git_pb2.PatchInfo]] = ...,
        changes: typing.Optional[typing.Iterable[global___LocustChange]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["changes",b"changes","initial_ref",b"initial_ref","patches",b"patches","repo",b"repo","terminal_ref",b"terminal_ref"]) -> None: ...
global___ParseResult = ParseResult
