"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import parse_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class IndexKey(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FILEPATH_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    LINE_FIELD_NUMBER: builtins.int
    REVISION_FIELD_NUMBER: builtins.int
    filepath: typing.Text
    name: typing.Text
    line: builtins.int
    revision: typing.Text
    def __init__(self,
        *,
        filepath: typing.Text = ...,
        name: typing.Text = ...,
        line: builtins.int = ...,
        revision: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filepath",b"filepath","line",b"line","name",b"name","revision",b"revision"]) -> None: ...
global___IndexKey = IndexKey

class NestedChange(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    KEY_FIELD_NUMBER: builtins.int
    CHANGE_FIELD_NUMBER: builtins.int
    CHILDREN_FIELD_NUMBER: builtins.int
    @property
    def key(self) -> global___IndexKey: ...
    @property
    def change(self) -> parse_pb2.LocustChange: ...
    @property
    def children(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___NestedChange]: ...
    def __init__(self,
        *,
        key: typing.Optional[global___IndexKey] = ...,
        change: typing.Optional[parse_pb2.LocustChange] = ...,
        children: typing.Optional[typing.Iterable[global___NestedChange]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["change",b"change","key",b"key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["change",b"change","children",b"children","key",b"key"]) -> None: ...
global___NestedChange = NestedChange
