name: Lint Python code

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Mypy type check
        run: mypy locust/
      - name: Black syntax check
        run: black --check --exclude '(.*_pb2.*|build|dist)' locust/
