name: Locust summary

on: [ pull_request_target ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: PR head repo
        id: head_repo_name
        run: |
          HEAD_REPO_NAME=$(jq -r '.pull_request.head.repo.full_name' "$GITHUB_EVENT_PATH")
          echo "PR head repo: $HEAD_REPO_NAME"
          echo "::set-output name=repo::$HEAD_REPO_NAME"
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          repository: ${{ steps.head_repo_name.outputs.repo }}
          fetch-depth: 0
      - name: Generate Locust summary
        uses: kompotkot/locust-action@v0.1.6
        id: locust
        with:
          format: json
      - name: Upload locust results to Bugout
        env:
          BUGOUT_SECRET: ${{ secrets.BUGOUT_SECRET }}
        run: |
          curl -k -X POST "https://spire.bugout.dev/github/summary" \
            -H "Content-Type: application/json" \
            -H "x-bugout-secret: $BUGOUT_SECRET" \
            --data '${{ steps.locust.outputs.summary }}'
